Django/project/getcare/website/getcareapp/urls.py
from django.urls import path

from . import views

app_name = 'getcare'

urlpatterns = [
    path('',views.login, name='login'),  
    path('register/',views.register, name='register'),
    path('login/',views.login, name='login'),
    path('<str:currentKey>/index/<str:classTask>', views.index, name='index'),
    path('<str:currentKey>/newtask/', views.newTask, name='newtask'),
    path('<str:currentKey>/viewtask/<int:task_id>', views.viewtask, name='viewtask'),
    path('<str:currentKey>/info/', views.info, name='info'),
    path('<str:currentKey>/viewnote/<int:note_id>',views.viewnote, name='viewnote'),
    path('<str:currentKey>/newnote/', views.newnote, name='newnote'),
    

]

Django/project/getcare/website/website/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('getcare/',include('getcareapp.urls'))
]

Django/project/getcare/website/getcareapp/models.py
from django.db import models
from django.utils import timezone

class Provider(models.Model):
    firstName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    gender = models.CharField(max_length=1)
    password = models.CharField(max_length=128)
    jobType = models.CharField(max_length=15)  #CARE\MEDICATION\COMMUNICATION\ACTIVITY\MEAL\OTHER
    email = models.CharField(max_length=128)
    phone = models.CharField(max_length=13)
    key = models.CharField(max_length=62)
    relation_code = models.CharField(max_length=10, default='1234567890')

    def __str__(self):
        return self.firstName + " " +self.lastName

class User(models.Model):
    firstName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    gender = models.CharField(max_length=1)
    password = models.CharField(max_length=128)
    email = models.CharField(max_length=128)
    phone = models.CharField(max_length=13)
    key = models.CharField(max_length=62) #62-bit key used to verify user login
    carer = models.ForeignKey("Carer",on_delete=models.CASCADE,related_name='+', null =True)
    # Providers
    careProvider = models.ForeignKey(Provider, on_delete=models.CASCADE,related_name='+', null = True)
    medicationProvider = models.ForeignKey(Provider, on_delete=models.CASCADE,related_name='+', null = True)
    communicationProvider = models.ForeignKey(Provider, on_delete=models.CASCADE,related_name='+', null = True)
    activityProvider = models.ForeignKey(Provider, on_delete=models.CASCADE,related_name='+', null = True)
    mealProvider = models.ForeignKey(Provider, on_delete=models.CASCADE,related_name='+', null = True)

    def __str__(self):
        return self.firstName + " " +self.lastName

class Carer(models.Model):
    firstName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    gender = models.CharField(max_length=1)
    password = models.CharField(max_length=128)
    email = models.CharField(max_length=128)
    phone = models.CharField(max_length=13)
    key = models.CharField(max_length=62) #62-bit key used to verify user login
    User = models.ForeignKey(User,on_delete=models.CASCADE,related_name='+', null = True)
    relation_code = models.CharField(max_length=10, default='1234567890')

    def __str__(self):
        return self.firstName + " " +self.lastName



class Tasks(models.Model):
    title = models.CharField(max_length=50)
    classTask = models.CharField(max_length=20, default="None")
    detail = models.TextField()
    create_date = models.DateField()
    start_date = models.DateField()
    Finish_date = models.DateField(null = True)
    user = models.ForeignKey("User",on_delete=models.CASCADE,related_name='+', null =True)
    carer = models.ForeignKey("Carer",on_delete=models.CASCADE,related_name='+', null =True)
    provider = models.ForeignKey("Provider",on_delete=models.CASCADE,related_name='+', null =True)
    status = models.IntegerField(default=0) # 1 = Finished this task; 0 = Not Finish this task
    comments = models.TextField(null = True)
    start_time = models.TimeField(null = True)
    end_time = models.TimeField(null = True)
    def __str__(self):
        return self.title


class List(models.Model):
    title = models.CharField(max_length=50)
    list_id = models.CharField(max_length=10, default='1234567890')
    User = models.ForeignKey(User,on_delete=models.CASCADE,related_name='+', null = True)


class Notes(models.Model):
    title = models.CharField(max_length=50)
    detail = models.TextField()
    create_date = models.DateField()
    start_date = models.DateField()
    Finish_date = models.DateField(null = True)
    user = models.ForeignKey("User",on_delete=models.CASCADE,related_name='+', null =True)
    carer = models.ForeignKey("Carer",on_delete=models.CASCADE,related_name='+', null =True)
    provider = models.ForeignKey("Provider",on_delete=models.CASCADE,related_name='+', null =True)
    status = models.IntegerField(default=0) # 1 = Finished this task; 0 = Not Finish this task
    start_time = models.TimeField(null = True)
    end_time = models.TimeField(null = True)
    def __str__(self):
        return self.title



import hashlib
import time

class key_generator(models.Model):

    def Generate_key(self, keystr):
        ''' Generate a UUID by the given key string. Key string: name, birthdate, register date.'''

        SHA1_str = hashlib.sha1(keystr.encode("utf-8"))
        encrypts = SHA1_str.hexdigest()
        return encrypts


    def Generate_time_key(self):
        ''' Generate a UUID by the accessing time. '''
        current_time = str(time.time())
        SHA1_str = hashlib.sha1(current_time.encode("utf-8"))
        encrypts = SHA1_str.hexdigest()
        return encrypts


    def Generate_combination_key(self,keystr):
        ''' Generate a 40-digits UUID conbining time and user key (name, birthdate, register date).
        Split the time key and user key into 4 segments respectively (10 digits per segment).
        The combined UUID will consist of: time seg4 + user key seg1 + time seg3 + user key seg 4 '''
        time_key = models.Generate_time_key(self)
        user_key = models.Generate_key(self,keystr)
        encrypt_str = time_key[30:40] + user_key[0:10] + time_key[20:30] + user_key[30:40]
        return encrypt_str

Django/project/getcare/website/getcareapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
from django.utils import timezone
from django.urls import reverse
import random
import string
from django.core.exceptions import ObjectDoesNotExist

def getCarerbyKey(currentKey):
    try:
        return Carer.objects.get(key = currentKey)
    except ObjectDoesNotExist:
        return False

def getUserbyKey(currentKey):
    try:
        return User.objects.get(key = currentKey)
    except ObjectDoesNotExist:
        return False

def getProviderbyKey(currentKey):
    try:
        return Provider.objects.get(key = currentKey)
    except ObjectDoesNotExist:
        return False

def findingUser(currentKey):
    current_user = getUserbyKey(currentKey)
    userType = "USER"
    if (current_user == False):
        current_user = getCarerbyKey(currentKey)
        userType = "CARER"
    if (current_user == False):
        current_user = getProviderbyKey(currentKey)
        userType = "PROVIDER"
    if (current_user == False):
        userType = "NONE"
    return current_user, userType

def findingTasks(currentUser, userType):
    user_tasks = ""
    if userType == "USER":
        user_tasks = Tasks.objects.filter(user = currentUser)
    elif userType == "CARER":
        user_tasks = Tasks.objects.filter(carer = currentUser)
    elif userType == "PROVIDER":
        user_tasks = Tasks.objects.filter(provider = currentUser)
    return user_tasks

def findingNotes(currentUser, userType):
    user_notes = ""
    if userType == "USER":
        user_tasks = Notes.objects.filter(user = currentUser)
    elif userType == "CARER":
        user_tasks = Notes.objects.filter(carer = currentUser)
    elif userType == "PROVIDER":
        user_tasks = Notes.objects.filter(provider = currentUser)
    return user_notes

def getUserbyEmail(currentEmail):
    try:
        return User.objects.get(email = currentEmail)
    except ObjectDoesNotExist:
        return False

def getCarerbyEmail(currentEmail):
    try:
        return Carer.objects.get(email = currentEmail)
    except ObjectDoesNotExist:
        return False

def getProviderbyEmail(currentEmail):
    try:
        return Provider.objects.get(email = currentEmail)
    except ObjectDoesNotExist:
        return False

def getTask(taskID, userKey):
    current_user, userType = findingUser(userKey)
    
    if userType == "USER":
        user_tasks = Tasks.objects.filter(user = current_user)
    elif userType == "CARER":
        user_tasks = Tasks.objects.filter(carer = current_user)
    elif userType == "PROVIDER":
        user_tasks = Tasks.objects.filter(provider = current_user)

    for user_task in user_tasks:
        if user_task.id == taskID:
            return Tasks.objects.get(id=taskID)
    return False

def getNote(noteID, userKey):
    current_user, userType = findingUser(userKey)
    
    if userType == "USER":
        user_notes = Notes.objects.filter(user = current_user)
    elif userType == "CARER":
        user_notes = Notes.objects.filter(carer = current_user)
    elif userType == "PROVIDER":
        user_notes = Notes.objects.filter(provider = current_user)

    for user_note in user_notes:
        if user_note.id == noteID:
            return Notes.objects.get(id=noteID)
    return False

def register(request):
    if request.method =="GET":
        return render(request,'GetCare/register.html')
    
    # random the key
    seed = string.ascii_letters + string.digits
    key = random.sample(seed,62)
    all_user = User.objects.all()
    i = 0
    key_list = []
    for i in range(len(all_user)):
        key_list.append(all_user[i].key)
    while key in key_list:
        key = random.sample(seed,62) 
    
    if request.POST['role'] == 'senoir':
        if request.POST['relationCode'] =='':
            return HttpResponse("Please enter your relation code")
        try:
            mycarer = Carer.objects.get(relation_code = request.POST['relationCode'])
        except ObjectDoesNotExist:
            return HttpResponse("We cannot find this relation code in our system")
        
        User.objects.create(firstName = request.POST['FirstName'], 
                            lastName = request.POST['LastName'], 
                            email = request.POST['email'], 
                            password = request.POST['password'], 
                            gender = request.POST['gender'], 
                            phone = request.POST['phone'], 
                            key = "".join(key),
                            carer = mycarer,
                            )
        mycarer.User = User.objects.get(email = request.POST['email'])
        mycarer.save()
        return HttpResponse(r"Successful.<br><a href=\getcare\login> Login </a>")
    elif request.POST['role'] == 'carer':
        relationCode = random.randint(0,999999)
        Carer.objects.create(firstName = request.POST['FirstName'], 
                            lastName = request.POST['LastName'], 
                            email = request.POST['email'], 
                            password = request.POST['password'], 
                            gender = request.POST['gender'], 
                            phone = request.POST['phone'], 
                            key = "".join(key),
                            relation_code = relationCode,)
        return HttpResponse("Successful. Your reflation code for senior is " + str(relationCode) + r"<br><a href=\getcare\login> Login </a>")
    elif request.POST['role'] == 'provider':
        relationCode = random.randint(0,999999)
        Provider.objects.create(firstName = request.POST['FirstName'], 
                            lastName = request.POST['LastName'], 
                            email = request.POST['email'], 
                            jobType = request.POST['jobType'], 
                            password = request.POST['password'], 
                            gender = request.POST['gender'], 
                            phone = request.POST['phone'], 
                            key = "".join(key),
                            relation_code = relationCode,)
        return HttpResponse("Successful. Your relation code for senior is " + str(relationCode) + r"<br><a href=\getcare\login> Login </a>")


def index(request, currentKey, classTask):
    
    # Finding current user by Key
    current_user, userType = findingUser(currentKey)
    if (current_user == False):
        return HttpResponse("Invalid key" + r"<br><a href=\getcare\login> Login </a>")
    # Loading current user Tasks
    User_tasks = findingTasks(current_user, userType)

    # Loading current user Notes.
    User_notes = findingNotes(current_user, userType)

    # Filting tasks which should be display
    result_tasks = []
    if classTask == "ALL" or classTask == "INCOMPLETED":
        for i in User_tasks:
            if i.status == 0:
                result_tasks.append(i)
    elif classTask == "COMPLETED":
        for i in User_tasks:
            if i.status == 1:
                result_tasks.append(i)
    else:            
        for i in User_tasks:
            if i.classTask == classTask and i.status == 0:
                result_tasks.append(i)

    result_notes = []    
    for i in User_notes:
        result_notes.append(i)


    if userType == "USER":
        return render(request,'GetCare/index.html',{'user': current_user,'Tasks':result_tasks})
    elif userType == "CARER":
        return render(request,'GetCare/index_carer.html',{'user': current_user,'Tasks':result_tasks})
    elif userType == "PROVIDER":
        return render(request,'GetCare/index_provider.html',{'user': current_user,'Tasks':result_tasks})
    else:
        return render(request,'GetCare/index.html',{'user': current_user,'Tasks':result_tasks})

    if userType == "USER":
        return render(request,'GetCare/index.html',{'user': current_user,'Notes':result_notes})
    elif userType == "CARER":
        return render(request,'GetCare/index_carer.html',{'user': current_user,'Notes':result_notes})
    elif userType == "PROVIDER":
        return render(request,'GetCare/index_provider.html',{'user': current_user,'Notes':result_notes})
    else:
        return render(request,'GetCare/index.html',{'user': current_user,'Notes': result_notes})



def login(request):
    if request.method == "GET":
        return render(request,'GetCare/login.html')

    currentEmail = request.POST.get('email')
    typePassword = request.POST.get('password')

    if request.POST.get('role') =='senoir':    
        current_user = getUserbyEmail(currentEmail)
        if current_user:
            if current_user.password == typePassword:
                return HttpResponseRedirect("/getcare/" + current_user.key + "/index/ALL")
    elif request.POST.get('role') =='carer':
        current_user = getCarerbyEmail(currentEmail)
        if current_user:
            if current_user.password == typePassword:
                return HttpResponseRedirect("/getcare/" + current_user.key + "/index/ALL")
    elif request.POST.get('role') =='provider':
        current_user = getProviderbyEmail(currentEmail)
        if current_user:
            if current_user.password == typePassword:
                return HttpResponseRedirect("/getcare/" + current_user.key + "/index/ALL")
    

    
    return HttpResponse(r"User information error.<br><a href=\getcare\login> Try agian </a>")


def newTask(request,currentKey):
    current_user, userType = findingUser(currentKey)
    if request.method == "GET":
        if userType == "USER":
            return render(request,'GetCare/newtask.html',{'user':current_user})
        elif userType == "CARER":
            return render(request,'GetCare/newtask_carer.html',{'user':current_user})
        elif userType == "PROVIDER":
            return render(request,'GetCare/newtask_provider.html',{'user':current_user})
        else:

Django/project/getcare/website/getcareapp/templates/GetCare/index.html
<!-- 
{% if user %}
    {{Message}}<br>
{% endif %}
<br>
<a href="{% url 'getcare:login'  %}">Log off</a>
<p>Task List</p>
<a href="{% url 'getcare:newtask' user.key %}">Add a New Task</a>
<br><br>
{% if Tasks %}

    {% for task in Tasks %}
        <a href="{% url 'getcare:viewtask' user.key task.id %}">{{ task.title }} -- {{task.start_date}}</a><br>
    {% endfor %}

{% else %}
    <p>No Tasks are available.</p>
{% endif %}
{% if Notes %}

    {% for note in Notes %}
        <a href="{% url 'getcare:viewnote' user.key note.id %}">{{ note.title }} -- {{note.start_date}}</a><br>
    {% endfor %}

{% else %}
    <p>No Notes are available.</p>
{% endif %} -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
}
/* Bar */
.navbar {
  overflow: hidden;
  background-color: #4CAF50;
}

.navbar a {
  float: left;
  font-size: 16px;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

.dropdown {
  float: left;
  overflow: hidden;
}

.dropdown .dropbtn {
  font-size: 16px;  
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
}

.navbar a:hover, .dropdown:hover .dropbtn {
  background-color: #ddd;
  color: black;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  float: none;
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.dropdown-content a:hover {
  background-color: #ddd;
}

.dropdown:hover .dropdown-content {
  display: block;
}
.search {
  overflow: hidden;

}
.search input[type=text] {
  float:right;
  padding: 6px;
  margin-top: 8px;
  margin-right: 10px;
  border: none;
  font-size: 17px;
}
.profile{
  float:right;
  margin-right: 10px;
}
@media screen and (max-width: 600px) {
  .search a, .search input[type=text] {
    float: none;
    display: block;
    text-align: left;
    width: 100%;
    margin: 0;
    padding: 14px;
  }
  
  .search input[type=text] {
    border: 1px solid #ccc;  
  }
}

/* content */
.button {
  background-color: #ccc;
  color: rgb(36, 36, 36);
  border: none;
  font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
  padding: 10px 15px;
  text-align: center;
  text-decoration: none;
  font-size: 20px;
  cursor: pointer;
  position:absolute;
  margin-left: 1080px;
  margin-top: 15px;
}
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border:1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
</style>
</head>
<body>

<div class="navbar">
  <a href=""{% url 'getcare:index' user.key 'ALL' %}""><img src="{% static 'getcareapp/getcare2.png' %}" id="logo" height="20px" width="90px"/></a>
  <div class="dropdown">
    <button class="dropbtn">All Tasks 
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'getcare:index' user.key 'COMPLETED' %}">Completed</a>
      <a href="{% url 'getcare:index' user.key 'INCOMPLETED' %}">Incomplete</a>
      
    </div>
  </div> 

  <div class="dropdown">
    <button class="dropbtn">Notes 
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'getcare:index' user.key 'ALL' %}">All</a>
      
    </div>
  </div> 

  <div class="dropdown">
    <button class="dropbtn">Calendar 
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="#">Week View</a>
      <a href="#">Month View</a>
    </div>
  </div> 

  <div class="dropdown">
    <button class="dropbtn">Provider 
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'getcare:index' user.key 'ALL' %}">All</a>
      <a href="{% url 'getcare:index' user.key 'CAREPLAN' %}">Care Plan</a>
      <a href="{% url 'getcare:index' user.key 'MEDICATION' %}">Medication</a>
      <a href="{% url 'getcare:index' user.key 'COMMUNICATION' %}">Communication</a>
      <a href="{% url 'getcare:index' user.key 'ACTIVITY' %}">Activity</a>
      <a href="{% url 'getcare:index' user.key 'MEAL' %}">Meal</a>
      <a href="{% url 'getcare:index' user.key 'OTHER' %}">Other</a>
    </div>
  </div> 
  <div class="profile">
    <a href="{% url 'getcare:info' user.key %}">My Profile</a>
    <a href="{% url 'getcare:login' %}">LOG OFF</a>
    
  </div>
  <div class="search">
    <input type="text" placeholder="Search..">
  </div>
</div>
 <!-- content -->


    <button class="button" ><a href="{% url 'getcare:newtask' user.key %}">+ New Task</a></button>
    <table style= "margin-top:80px"  >
      <tr>
        <th style="text-align:center">Task</th>
        <th style="text-align:center">Provider</th>
        <th style="text-align:center">Deadline</th>
      </tr>
      {% if Tasks %}
        {% for task in Tasks %}
          <tr>
          <td>
          <input type="checkbox" id="vehicle1" name="vehicle1" value="Bike">
          <label for="task1"  style="font-size: 20px;"> <a href="{% url 'getcare:viewtask' user.key task.id %}">{{ task.title }}</a><br> </label>
          </td>
          <td style="text-align:center">
            <p for="person" >{{ task.provider.firstName}} {{ task.provider.lastName}}</p>
          </td>
          <td style="text-align:center">
            <p for="timestamp" class="time"> {{task.start_date}} </p>
          </td>    
          </tr>
        {% endfor %}
      {% else %}
          <p>No Tasks are available.</p>
      {% endif %}

    


    


    </table>
</body>
</html>

Django/project/getcare/website/getcareapp/templates/GetCare/index_carer.html
<!-- 
{% if user %}
    {{Message}}<br>
{% endif %}
<br>
<a href="{% url 'getcare:login'  %}">Log off</a>
<p>Task List</p>
<a href="{% url 'getcare:newtask' user.key %}">Add a New Task</a>
<br><br>
{% if Tasks %}

    {% for task in Tasks %}
        <a href="{% url 'getcare:viewtask' user.key task.id %}">{{ task.title }} -- {{task.start_date}}</a><br>
    {% endfor %}

{% else %}
    <p>No Tasks are available.</p>
{% endif %} -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
}
/* Bar */
.navbar {
  overflow: hidden;
  background-color:rgb(101,61,176);
}

.navbar a {
  float: left;
  font-size: 16px;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

.dropdown {
  float: left;
  overflow: hidden;
}

.dropdown .dropbtn {
  font-size: 16px;  
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
}

.navbar a:hover, .dropdown:hover .dropbtn {
  background-color: #ddd;
  color: black;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  float: none;
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.dropdown-content a:hover {
  background-color: #ddd;
}

.dropdown:hover .dropdown-content {
  display: block;
}
.search {
  overflow: hidden;

}
.search input[type=text] {
  float:right;
  padding: 6px;
  margin-top: 8px;
  margin-right: 10px;
  border: none;
  font-size: 17px;
}
.profile{
  float:right;
  margin-right: 10px;
}
@media screen and (max-width: 600px) {
  .search a, .search input[type=text] {
    float: none;
    display: block;
    text-align: left;
    width: 100%;
    margin: 0;
    padding: 14px;
  }
  
  .search input[type=text] {
    border: 1px solid #ccc;  
  }
}

/* content */
.button {
  background-color: #ccc;
  color: rgb(36, 36, 36);
  border: none;
  font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
  padding: 10px 15px;
  text-align: center;
  text-decoration: none;
  font-size: 20px;
  cursor: pointer;
  position:absolute;
  margin-left: 1080px;
  margin-top: 15px;
}
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border:1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
</style>
</head>
<body>

<div class="navbar">
  <a href=""{% url 'getcare:index' user.key 'ALL' %}""><img src="{% static 'getcareapp/getcare2.png' %}" id="logo" height="20px" width="90px"/></a>
  <div class="dropdown">
    <button class="dropbtn">All Tasks 
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'getcare:index' user.key 'COMPLETED' %}">Completed</a>
      <a href="{% url 'getcare:index' user.key 'INCOMPLETED' %}">Incompleted</a>
      
    </div>
  </div> 
  <div class="dropdown">
    <button class="dropbtn">Calendar 
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="#">Week View</a>
      <a href="#">Month View</a>
    </div>
  </div> 

  <div class="dropdown">
    <button class="dropbtn">Provider 
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'getcare:index' user.key 'ALL' %}">All</a>
      <a href="{% url 'getcare:index' user.key 'CAREPLAN' %}">Care Plan</a>
      <a href="{% url 'getcare:index' user.key 'MEDICATION' %}">Medication</a>
      <a href="{% url 'getcare:index' user.key 'COMMUNICATION' %}">Communication</a>
      <a href="{% url 'getcare:index' user.key 'ACTIVITY' %}">Activity</a>
      <a href="{% url 'getcare:index' user.key 'MEAL' %}">Meal</a>
      <a href="{% url 'getcare:index' user.key 'OTHER' %}">Other</a>
    </div>
  </div> 
  <div class="profile">
    <a href="{% url 'getcare:info' user.key %}">My Profile</a>
    <a href="{% url 'getcare:login' %}">LOG OFF</a>
    
  </div>
  <div class="search">
    <input type="text" placeholder="Search..">
  </div>
</div>
 <!-- content -->


    <button class="button" ><a href="{% url 'getcare:newtask' user.key %}">+ New Task</a></button>
    <table style= "margin-top:80px"  >
      <tr>
        <th style="text-align:center">Task</th>
        <th style="text-align:center">Senior</th>
        <th style="text-align:center">Deadline</th>
      </tr>
      {% if Tasks %}
        {% for task in Tasks %}
          <tr>
          <td>
          <input type="checkbox" id="vehicle1" name="vehicle1" value="Bike">
          <label for="task1"  style="font-size: 20px;"> <a href="{% url 'getcare:viewtask' user.key task.id %}">{{ task.title }}</a><br> </label>
          </td>
          <td style="text-align:center">
            <p for="person" >{{task.user.firstName}} {{task.user.lastName}}</p>
          </td>
          <td style="text-align:center">
            <p for="timestamp" class="time"> {{task.start_date}} </p>
          </td>    
          </tr>
        {% endfor %}
      {% else %}
          <p>No Tasks are available.</p>
      {% endif %}



    </table>
</body>
</html>